name: Umbraco Community Fallback

on: 
  push:
    branches:
      - 'main'

env:
  SourceFolder: src/Umbraco.Community.Fallback
  NuGetDirectory: ${{ github.workspace }}/nuget

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
      
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore $SourceFolder

      - name: Build
        run: dotnet build $SourceFolder --configuration Release --no-restore

      - name: Create the package
        run: dotnet pack --configuration Release $SourceFolder -p:PackageVersion=${{steps.version.outputs.version}} --output ${{ env.NuGetDirectory }}

      - name: Push the package
        run: dotnet push ${{env.SourceFolder}}/bin/Release/net7.0/Umbraco.Community.Fallback.${{steps.version.outputs.version}}.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key "${{ secrets.NUGET_APIKEY}}"